// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfxpP4EwYRLoKR_sba_sOpX8G9xX7JnLs',
    appId: '1:150083215099:web:527d3e76ed96d65e485a5e',
    messagingSenderId: '150083215099',
    projectId: 'clickme-406e8',
    authDomain: 'clickme-406e8.firebaseapp.com',
    storageBucket: 'clickme-406e8.firebasestorage.app',
    measurementId: 'G-7247T6HPBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4mquQX8Rvn29sZG3X2cd8s9m0ld8Y7k',
    appId: '1:150083215099:android:d4532e6003696328485a5e',
    messagingSenderId: '150083215099',
    projectId: 'clickme-406e8',
    storageBucket: 'clickme-406e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe81r2Js5U1HPRVSQAMCxojYdXjzsdeco',
    appId: '1:150083215099:ios:1da586413adb41da485a5e',
    messagingSenderId: '150083215099',
    projectId: 'clickme-406e8',
    storageBucket: 'clickme-406e8.firebasestorage.app',
    iosBundleId: 'com.example.clickMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe81r2Js5U1HPRVSQAMCxojYdXjzsdeco',
    appId: '1:150083215099:ios:1da586413adb41da485a5e',
    messagingSenderId: '150083215099',
    projectId: 'clickme-406e8',
    storageBucket: 'clickme-406e8.firebasestorage.app',
    iosBundleId: 'com.example.clickMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfxpP4EwYRLoKR_sba_sOpX8G9xX7JnLs',
    appId: '1:150083215099:web:2f89a592e1822cc3485a5e',
    messagingSenderId: '150083215099',
    projectId: 'clickme-406e8',
    authDomain: 'clickme-406e8.firebaseapp.com',
    storageBucket: 'clickme-406e8.firebasestorage.app',
    measurementId: 'G-9D5XK8B4P0',
  );
}
